#!/bin/bash
total 16
-rwxr--r-- 1 root root 16 Feb  8 18:53 0-current_working_directory   
-rwxr--r-- 1 root root 61 Feb  9 02:05 1-listit
-rwxr--r-- 1 root root 17 Feb  9 08:17 2-bring_me_home
-rw-r--r-- 1 root root 13 Feb  8 18:46 README.md
